server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: consul
      enabled: true
      discovery:
        # Get only services that are passing the health check
        query-passing: true
    gateway:
      mvc:
        routes:
          - id: post
            uri: lb://post/
            predicates:
              - Path=/posts/**
          - id: timeline
            uri: lb://timeline/
            predicates:
              - Path=/timeline/**
          - id: user
            uri: lb://user/
            predicates:
              - Path=/users/**
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "*"
              allowedHeaders:
                - "*"
              allowedMethods:
                - "GET"
                - "POST"
          default-filters:
            - name: Retry
              args:
                retries: 3
                methods: GET,POST